#!/bin/bash

source config

if [ ! -d $T ]; then
    mkdir $T
fi
if [ ! -d $D ]; then
    mkdir $D
fi

time0=`date "+%Y-%m-%d-%H-%M-%S"`
logfile=${LOG}/${time0}.log
echo $APP -t $T -d $D -r $R -f $F -p $P
echo $logfile
$APP -t $T -d $D -r $R -f $F -p $P > $logfile 2>&1
echo $!
total=`grep 'Total time' $logfile|awk '{print $4}' | awk '{print int($1)}'`
if [ -n "$total" ];
then
  hour=$((${total}/3600))
  ./sendmsg $hour $D
fi